name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get AWS Account ID
      id: aws
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: docker build -t backend-eks:${{ github.sha }} .

    - name: Tag Image
      run: |
        docker tag backend-eks:${{ github.sha }} \
        ${{ env.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend-eks:${{ github.sha }}

    - name: Push Image
      run: |
        docker push \
        ${{ env.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend-eks:${{ github.sha }}

    # ---------------------------
    # ðŸ”¥ EKS DEPLOYMENT SECTION
    # ---------------------------

    - name: Update kubeconfig (connect to EKS)
      run: |
        aws eks update-kubeconfig \
          --region us-east-1 \
          --name ${{ secrets.CLUSTER_NAME }}

    - name: Update deployment image
      run: |
        kubectl set image deployment/backend-deployment \
        backend=${{ env.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend-eks:${{ github.sha }}

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/
