name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t node-backend:${{ github.sha }} .

    - name: Tag Image
      run: |
        docker tag node-backend:${{ github.sha }} \
        <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/node-backend:${{ github.sha }}

    - name: Push Image
      run: |
        docker push <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/node-backend:${{ github.sha }}

    - name: Checkout GitOps Repo
      uses: actions/checkout@v3
      with:
        repository: shankarprem12/gitops
        token: ${{ secrets.GITOPS_PAT }}

    - name: Update Helm values.yaml
      run: |
        sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/" charts/backend/values.yaml

    - name: Commit & Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update image tag to ${{ github.sha }}"
        git push
